# Project information
site_name: KidsBlock
site_url: https://KidsBlock.gitee.io/en/
site_author: KidsBlock
site_description: >-
  KidsBlock wiki

# Repository
repo_name: KidsBlock/KidsBlock.github.io
repo_url: https://github.com/KidsBlock/KidsBlock.github.io/tree/en

# Configuration
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
  icon:
    logo: material/library
  favicon: assets/favicon.png
  logo: 'assets/logo.svg'

# Copyright
copyright: Copyright &copy; 2022 - 2023 KidsBlock

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KidsBlock
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Page tree
nav:
  - Home Page: 
    - introduce: index.md
    - characteristic: features.md
  - Download and Install:
    - download: download.md
    - install: 
      - for Windows: Windows.md
      - for MacOS: MacOS.md
    - install driver: driver.md
  - Quick Start:
    - description: description.md
    - interface: interface.md
    - function: function.md
  - Programming:
    - animation mode: cartoon.md
    - realtime mode: realtime.md
    - upload mode: upload.md
  - Tutorial:
    - smart traffic: 
       - Project 01: traffic/Project1.md
       - Project 02: traffic/Project2.md
       - Project 03: traffic/Project3.md
       - Project 04: traffic/Project4.md
       - Project 05: traffic/Project5.md
       - Project 06: traffic/Project6.md
       - Project 07: traffic/Project7.md
       - Project 08: traffic/Project8.md
 